name = "surpriseme-app"
compatibility_date = "2024-11-19"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "surpriseme-db"
database_id = "72f1303c-2bc6-4da9-9a5d-624240a976f1"

[vars]
NUXT_PUBLIC_BASE_URL = "https://your-domain.pages.dev"